version: 2
updates:
  - package-ecosystem: npm
    commit-message:
      prefix: fix
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
