name: 'Unit Tests'
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        id: test
        uses: ./
        with:
          api_token: ${{ secrets.API_TOKEN }}
          debug: 'true'